### ISSUE TITLE
Consider *ownCloud Infinite Scale* to replace Nextcloud

### ISSUE THREAD

**Issue by NatoBoram** [NatoBoram/docker-compose#12]
* https://github.com/owncloud/ocis

**Comment by NatoBoram** [comment]
Started with something like this but I guess it won't be that simple. Removing it from `main`.
```yaml
services:
  ocis:
    container_name: ocis
    image: owncloud/ocis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```
