### ISSUE TITLE
Consider ToCry to replace Nextcloud Deck

### ISSUE THREAD

**Issue by NatoBoram** [NatoBoram/docker-compose#43]
* https://github.com/ralsina/tocry

**Comment by NatoBoram** [comment]
ToCry was tried in its `v0.2`, it's a bit unfair to compare it to the others.

Despite this, absolute GGs to the maintainer.

- [x] Not in PHP
- [x] Legible
- [x] Mobile-friendly
- [x] Dark and light themes
- [ ] Markdown editor
- [x] Drag & drop
- [x] Arbitrary columns
- [ ] Arbitrary labels
- [ ] Users
  - [ ] Board creation
  - [ ] User permissions
- [ ] Comments
- [ ] File and image uploads
- [ ] SSO

```yaml
services:
  tocry:
    container_name: tocry
    depends_on:
      - caddy
    image: ghcr.io/ralsina/tocry
    networks:
      - caddy-tocry
    restart: always
    volumes:
      - tocry:/data

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  tocry:
```
